### ISSUE TITLE
Error during execution of "config_generator.py" file.

### ISSUE THREAD

**Issue by Santan47** [fossasia/susi_linux#105]
![json bug in susi1](https://user-images.githubusercontent.com/19388036/40068988-97b565a6-5887-11e8-8c17-57bd9e98cd13.jpg)
no module named as json_config.

**Comment by stealthanthrax** [comment]
@Santan47 , did you execute install.sh file??

**Comment by Santan47** [comment]
Hi @stealthanthrax , yes I executed the install script in susi_linux folder.


![install sh1 problem](https://user-images.githubusercontent.com/19388036/40116114-442c35aa-5930-11e8-8bb9-e60dab399301.jpg)


I am using ubuntu 14.04 OS and after execution of install.sh  I got an output like this.
There are some packages which are not installed in the execution and showing me error.
so can you tell me how can i resolve this error.

**Comment by hongquan** [comment]
You are using too old Ubuntu (14.04), which doesn't have suitable software.

**Comment by prateekiiest** [comment]
is this issue resolved, may be we can close this
