### ISSUE TITLE
Cairo not supported with latest Raspbian

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#106]
On running the command ```` python3 app.py ````
It returns an error of importing Cairo
And on ```` pip3 install Cairo  ````
It returns an error saying 'no compatible versions found
I fixed this by importing cairociff instead of cairo.

**Comment by stealthanthrax** [comment]
@Orbiter @betterclever , are you guys facing this bug too or is just in mine?

**Comment by hongquan** [comment]
`cairo` should not be installed via `pip`. It should be installed via `apt`.

```
sudo apt install python3-cairo
```

**Comment by stealthanthrax** [comment]
Thank you @hongquan , this solves the issue
