### ISSUE TITLE
Deploying a local server on the raspberry Pi

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#111]
**Actual Behaviour**

Only online server available in the wrapper

**Expected Behaviour**

To configure it with a local server

**LogCat for the issue**

Right now , while deploying the server on the raspberry pi , I am getting an error:
````
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
````

**Would you like to work on the issue?**

Yes but first, I'll fix the above issue and the continue with the deployment
This issue requires this [issue](https://github.com/fossasia/susi_api_wrapper/issues/33) being solved in python api wrapper

**Comment by betterclever** [comment]
@hongquan The Susi Linux client is written in Python, the actual Susi server runs on Java. The issue is about deploying full Susi Server on the Client.

**Comment by stealthanthrax** [comment]
Fixed Here : [link](https://github.com/fossasia/susi_linux/pull/118)
