### ISSUE TITLE
To add a data parser to play audio

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#119]
**Actual Behaviour**

Now the skill to play audio has been made and hence should be done in the client

**Expected Behaviour**

To play audio through the client. 
I plan to use vlc api for playing the audio.

**Would you like to work on the issue?**

Yes

**Comment by stealthanthrax** [comment]
This issue is fixed here fossasia/susi_api_wrapper#36

**Comment by Orbiter** [comment]
I recommend not to use any api to play audio which requires a GUI or any X libraries. We want that the linux on the raspi is small. We should avoid to use libraries which are not required on a headless system. Please use a headless player.

**Comment by Orbiter** [comment]
You can use the "play" command from the sox library, see:
https://packages.debian.org/sid/sox

This library is already mentioned in the susi_linux documentation, so it should be obvious that this can be used. The command is also already used in the project.

**Comment by stealthanthrax** [comment]
Thanks @Orbiter , I'll use `sox` instead.

**Comment by stealthanthrax** [comment]
Fixed here : [link](https://github.com/fossasia/susi_linux/pull/168)
