### ISSUE TITLE
To try to Create Raspi as a wireless access point

### ISSUE THREAD

**Issue by sansyrox** [fossasia/susi_linux#120]
**Actual Behaviour**
No actual way to connect the hardware to SUSI-Android/IOS app

**Expected Behaviour**

To allow the raspberryPi to work as a WAP for initialization through the app
 

**Would you like to work on the issue?**
Yes

**Comment by Orbiter** [comment]
See issues for 
iOS: https://github.com/fossasia/susi_iOS/issues/287
Android: https://github.com/fossasia/susi_android/issues/1250

please work tightly together.
