### ISSUE TITLE
Best Strategy to put together SUSI images

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_linux#13]
Susi Hardware has a dependency on Libraries like PocketSphinx which takes a long amount of time to install on a Raspberry Pi and similar under- powered development boards (since they are needed to be compiled from source).
We have some potential solutions to save end users from going through the trouble:
- Like Mycroft project (https://mycroft.ai), we can ship the solution as a compressed images with all dependencies.
- Compile a packaged binary for dependencies like PocketSphinx for Raspberry Pi, and distribute it. Users can then install it directly without need to install it from source.

I am looking for better strategies and currently working on fulfilling first.

**Comment by mariobehling** [comment]
I think this issue is not about hardware distribution per se. It is actually about the software images. You are raising an important point, but we can also decide this finally later and see what works best for the moment.

**Comment by betterclever** [comment]
@mariobehling  Yes, thanks for correcting the title.  It should have been that at the first place. I raised this issue early so that as we proceed along the project as we find better ideas, we may have a list here in the tracker.

**Comment by mariobehling** [comment]
@stealthanthrax Let's follow up on this now. How can we get a custom image with SUSI to be installed on an SD Card?

**Comment by woshikie** [comment]
For Raspberry Pi, we can use [Win32DiskImager](https://sourceforge.net/projects/win32diskimager/) to copy the partition and settings on a Pi into a `.img` file and we can use the same `.img` file to populate new SD Cards using the same program

**Comment by stealthanthrax** [comment]
@woshikie , but first I think we should follow a way (that @Orbiter suggested) to remove x11 libraries from raspbian and make it a minimal environment

**Comment by woshikie** [comment]
There's Raspbian Lite

**Comment by hongquan** [comment]
We can use Raspbian build script, basing our custom image on Raspbian Lite, adding some modification to let it install some dependencies to the image.

**Comment by stealthanthrax** [comment]
@woshikie @hongquan  , there is also an inbuilt SD card copier in Raspbian, I used that everything worked fine. I think that should also be taken into account

**Comment by stealthanthrax** [comment]
@hongquan , how can we create a fresh image with just installed software??

**Comment by hongquan** [comment]
@stealthanthrax https://github.com/fossasia/susi_linux/issues/323

> Customize Raspbian build script to create image file, including our stuff.

**Comment by mariobehling** [comment]
We are following: http://www.yacy-websearch.net/wiki/index.php/En:DebianHeadless

**Comment by hongquan** [comment]
We are following these steps #349 . I haven't made a detail documentation yet.
