### ISSUE TITLE
To check the frequency of update daemon

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#152]
**Actual Behaviour**

One has to manually trigger the update daemon

**Expected Behaviour**

To update the server and skill_Data with a fixed frequency(How regularly should the speaker check for updates).

**Would you like to work on the issue?**

Yes

**Comment by stealthanthrax** [comment]
The frequency as of now is decided as whenever the Pi boots up

**Comment by woshikie** [comment]
Closing as the frequency has been decided
