### ISSUE TITLE
To document the workflow of connection between Smart speaker and IOS/Android App

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#172]
**Actual Behaviour**

No documentation present

**Expected Behaviour**

To add documentation

**Would you like to work on the issue?**

Yes

**Comment by Orbiter** [comment]
![susi_connection_process](https://user-images.githubusercontent.com/238730/41810086-df6f49e0-76f8-11e8-924b-afcd50ca091f.JPG)

I tried to draw the process. Please discuss.

**Comment by mariobehling** [comment]
Yes, this is the plan.

**Comment by Orbiter** [comment]
When the Susi Device is creating it's own hot spot, we should use a fixed name for that so its easier to identify that the Android/IOs device has actually found the right one. Lets call the ssid "susi.ai", that would create some advertisement in the very moment when the hotspot is on.

**Comment by mariobehling** [comment]
Yes, please use it in caps "SUSI.AI".

**Comment by mariobehling** [comment]
Unfortunately SVGs don't display on github. Please add the svg code into an independent file in the folder `docs/images` and use "rawgit.com" to add it into the Readme.md.
