### ISSUE TITLE
To correct the folder architecture of speaker

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#176]
**Actual Behaviour**

Currently, the path is hardcoded as `/home/pi/SUSI.AI`

**Expected Behaviour**

To choose a better path

**Would you like to work on the issue?**

Yes

**Comment by stealthanthrax** [comment]
@mariobehling @Orbiter @hongquan , instead of changing the path to `/home/SUSI.AI` as it will require a lot of different privileges, we can use `$HOME/SUSI.AI` and by default, $HOME is set to `/home/pi` in the raspberry pi.

**Comment by mariobehling** [comment]
Ok, sounds good. However, this needs to be revisited as we are not only focusing on PIs and we need to adapt this in future for other devices. Thanks.
