### ISSUE TITLE
To decide the required digital amplifier

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#195]
**Actual Behaviour**

No digital amplifier is being used

**Expected Behaviour**

To decide an external digital amplifier required

**Would you like to work on the issue?**

**Comment by woshikie** [comment]
I was thinking about [https://www.adafruit.com/product/1712](this i2c amplifier from Adafruit)

**Comment by cweitat** [comment]
https://www.adafruit.com/product/3006
Looking at this as alternative as well

**Comment by woshikie** [comment]
https://github.com/respeaker/seeed-voicecard/issues/39
looks like the re-speaker already has a built-in speaker. I am going to test the loudness

**Comment by woshikie** [comment]
Tested both 2W8Ω and 1W8Ω speakers by connecting them raw (no additional amplifier) to the respeaker's Speaker Out port by soldering two extra jumper cables to the back of the JST 2.0 Male Port.

Both speakers works well and tested to be able to hear at about 5 metres away. The microphone is also picking up echos from the speaker at the same distance.

**Comment by woshikie** [comment]
https://www.robot-r-us.com/components/digital-potentiometer-10k.html

**Comment by mariobehling** [comment]
We are sticking with Respeaker 2 Head for now.
