### ISSUE TITLE
More Installation Errors on Raspbian Scratch

### ISSUE THREAD

**Issue by woshikie** [fossasia/susi_linux#206]
**Describe the bug**
Installation Errors on Raspberry Pi Zero W

**To Reproduce**
1. Flash a new version of raspbian to raspberry pi
2. Clone susi_linux repo
3. Run install.sh

**Expected behavior**
A smooth installation without errors

**Screenshots**

- Original Log
[Terminal Log (Pastebin)](https://pastebin.com/GdWWNHBh)
- After #212 
[Terminal Log (Pastebin)](https://pastebin.com/SzixK752)
- After Meeting on 03/07/18
[Terminal Log (Pastebin)](https://pastebin.com/3hF0VQBd)
- Install Attempt on 06/07/18
[Terminal Log (Pastebin)](https://pastebin.com/TuK6aHYJ)

**Additional context**
A different error occurs on ubuntu 18.04 LTS (#208 )

**Comment by stealthanthrax** [comment]
@woshikie , would you like to work on these issues, or can these be assigned to someone else?

**Comment by woshikie** [comment]
@stealthanthrax I'd love to, but I have some questions.
1) why is graddle needed? Isn't susi a python app? 
2) why is the local server started automatically? 
3) i ran into some issues after this, can you help?

**Comment by stealthanthrax** [comment]
@woshikie ,
1> Our main SUSI server is made in JAVA hence we need a gradle to build and deploy it locally.
2> The local server is started automatically since we are using the local server as the default, so we'll try and connect to it every time
3> I can try and solve issue #207 ??

**Comment by stealthanthrax** [comment]
@woshikie , the local server increases the efficiency by around 20% and if there is a failure in local server : say a build failure , we switch to the online server

**Comment by woshikie** [comment]
@stealthanthrax and what should happen if there's a build failure for the local server and the online server is offline for some reasons?

**Comment by stealthanthrax** [comment]
@woshikie , the user can do a soft reset to start the build again

**Comment by woshikie** [comment]
@stealthanthrax if the user is unable to build it the first time, how is it possible that the use is able to build it even after soft reseting?

**Comment by woshikie** [comment]
Reopened because issue is still happening

**Comment by stealthanthrax** [comment]
@woshikie , i am unable to replicate this bug. Please can you elaborate?

**Comment by woshikie** [comment]
@stealthanthrax i have updated the log

**Comment by stealthanthrax** [comment]
@woshikie , there are some updates made now , can you check again on the pi 0 ??

**Comment by woshikie** [comment]
@stealthanthrax gradle build still failed at 

- GeocodingTest > testNoTFound
- GeocodingTest > testGeocoding

**Comment by woshikie** [comment]
@stealthanthrax i have updated the log on the first post, please take a look

**Comment by stealthanthrax** [comment]
@woshikie , this a problem with pi zero's architecture and JVM version. I think this can be solved only from the server side repo

**Comment by woshikie** [comment]
workaround found for raspberry pi zero w

**Comment by woshikie** [comment]
Looks like java (oracle) that came with the raspberry pi does not support server mode on armv6.
To fix that, we have to install openjdk java8 (be careful not to install default-jdk because it will download the latest openjdk java, which is version 9. Java has dropped support for armv5/6/7 in java 9)
