### ISSUE TITLE
Errors when running config_generator.py

### ISSUE THREAD

**Issue by woshikie** [fossasia/susi_linux#207]
**Describe the bug**
Errors occured when running config_generator.py

**To Reproduce**
1. Flash a fresh version of Raspbian Image
2. Install SUSI on it, expect errors (#206).
3. Run `python3 config_generator.py`

**Expected behavior**
No errors and completes the configuration

**Screenshots**
```
pi@raspberrypi:~/susi_linux $ python3 config_generator.py
Traceback (most recent call last):
  File "config_generator.py", line 4, in <module>
    import json_config
ImportError: No module named 'json_config'
```
after install script fixes
```
pi@raspberrypizero:~/SUSI.AI/susi_linux $ python3 config_generator.py
Traceback (most recent call last):
  File "config_generator.py", line 166, in <module>
    if sys.argv[6] != 'y':
IndexError: list index out of range
```

**Comment by stealthanthrax** [comment]
@woshikie , you have to run `install.sh` file

**Comment by woshikie** [comment]
@stealthanthrax I already did

**Comment by hongquan** [comment]
The `json_config` seems to be installed somewhere by the _install.sh_, but this _install.sh_ failed on your machine, so you didn't get `json_config`. You have to install it manually.
