### ISSUE TITLE
Some bugs in the python server 

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#221]
**Describe the bug**
When the endpoints are called through the mobile app, the commands are received but the scripts are not executed

**To Reproduce**
Set Up SUSI smart speaker from Android App

**Expected behavior**
To fix this feature

**Desktop (please complete the following information):**
 - OS: Raspbian
 - Version Strech

**Would you like to work on this ISSUE**
Yes

**Comment by hongquan** [comment]
- Make title more specific. "Some bugs"? Which bug?
- The bug description is still vague. Which endpoints? Which command? Which script is not executed?
