### ISSUE TITLE
Create proper vector SVG image

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#229]
**Describe the bug**
@prateekiiest , when @mariobehling tell you to make diagram document in SVG, he wants a vector image, so that it comes as "source", can be edited, and can be scale. But why you make it in bitmap and just embed to SVG file? This is not honest.

**Expected behavior**
The file is a true SVG image, with lines and shapes being made by SVG code.

**Screenshots**
Current SVG source:

![image](https://user-images.githubusercontent.com/314607/42304066-8ffcb988-804e-11e8-9f6c-4b0060dfa323.png)

![image](https://user-images.githubusercontent.com/314607/42304091-bae71a94-804e-11e8-8aec-cf405adb3bad.png)

**Comment by prateekiiest** [comment]
@hongquan , @mariobehling did not assign me this issue for creating the svg . This was assigned to @stealranthx during one of the previous meetings as far as I remember. So he has made the update accordingly here #213.

So either it might have got changed while updating the base branch in one of my PRs or it has been updated by some one else. This happened without any intention of mine. Even if it was an accidental commit, I will make a PR soon to update the changes.

**Comment by hongquan** [comment]
Sorry, @prateekiiest.

**Comment by prateekiiest** [comment]
@hongquan @stealthanthrax please have a look at #290
