### ISSUE TITLE
Update the installation docs regarding configuring and running SUSI on the Raspberry Pi

### ISSUE THREAD

**Issue by Akshat-Jain** [fossasia/susi_linux#234]
I've been trying to setup Raspberry Pi 3 for several days now, and finally managed to configure and run SUSI on it yesterday. I think the installation docs are missing a few important steps. 
Hence, the installation docs should be updated with the proper procedure for configuring and running SUSI on the Raspberry Pi.

**Comment by woshikie** [comment]
Can you tell us what are the extra steps you took to install on your raspberry pi 3?

**Comment by Akshat-Jain** [comment]
@woshikie All the steps mentioned in the installation doc need to be executed once we're in the `SUSI.AI` folder, right? I can't find this info in the docs, and I actually spent a lot of time trying to execute the commands in the root directory itself. Also, the `install.sh` command should be run with `sudo` otherwise I was getting errors like permission denied. I think these minor things should be added in the docs. Thanks :-)

**Comment by woshikie** [comment]
the install.sh should **not** be ran with `sudo` because the `SUSI.AI` is not supposed to be touching any system settings or files

**Comment by Akshat-Jain** [comment]
@woshikie Running it without `sudo` was ending the script with `permission denied` error for me.

**Comment by stealthanthrax** [comment]
@Akshat-Jain , `sudo` issue is fixed now we can use it as it is
