### ISSUE TITLE
'Main' and 'config_generator.py' scripts are broken 

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#252]
**Describe the bug**
Right now after the installation , the commands `python3 -m main` and `python3 config_generator.py` exit out with errors. This is happening after the PR regarding the snowboy installation and its dependent PR is still WIP.
Which creates a blocker for the addition of other features

**To Reproduce**
1. Use installation script
2. Use command `python3 config_generator.py` and see error
3. Use command `python3 -m main` and see error

**Expected behavior**
To restore the repo in a working State and implement the **complete ** snowboy refactor in a single PR

**Additional context**
Yes

**Comment by hongquan** [comment]
@stealthanthrax @prateekiiest Did you guys read this comment of mine: https://github.com/fossasia/susi_linux/issues/215#issuecomment-402923779

> It will be good if you can combine these to 1 PR, so that it is not half-cooked and break the system.

I foresee that do just 1 of the steps will break the system, that is why I request to do all 3 steps in 1 PR. But you didn't follow. Where is the PR for the 3rd step?
