### ISSUE TITLE
Fix the "play" command to play audio file

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#254]
**Describe the bug**
From https://github.com/fossasia/susi_linux/pull/250/files, I found that there is use of play with command like this:

```sh
play /path/audiofile &
```
`&` is shell's operator and is only understood by shell, so  passing it to Python's `subprocess` like this will not work:

```py
subprocess.call(['play', '{0} &'.format(self.components.config['detection_bell_sound'])])
```

The whole `'/path/audiofile &'` string will be seen as file path and `sox` will not able to find the file to play.

**What to do**

1. Check again if we really need the feature of shell `&` operator.
2. If it is needed, implement that feature in Python (without using shell).

**Comment by stealthanthrax** [comment]
I can try and work on it
