### ISSUE TITLE
Main script doesn't run without a pi hat

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#260]
**Describe the bug**
The main script works only with pi hat , but throws as error without it and has some errors with snowboy refactor

**Expected behavior**
To make it work without it again

**Would you like to work on it?**
Yes

EDIT
Error Log
<img width="643" alt="screenshot 2018-07-15 at 11 46 58 pm" src="https://user-images.githubusercontent.com/29942790/42736875-13959898-888b-11e8-9576-9c45d517a35f.png">

**Comment by hongquan** [comment]
Please give an error log.

**Comment by stealthanthrax** [comment]
@hongquan , I have updated the log
