### ISSUE TITLE
To configure a button on GPIO 17

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#274]
**Is your feature request related to a problem? Please describe.**
To configure the button present on the respeaker , port 17 to function as mic mute on a single click and factory reset on a long click(>7 second)

**Describe alternatives you've considered**
This should be part of the factory reset daemon. In this approach, a python script will be running in the background which will detect if the button has been triggered. And do the functions stated above

**Would you like to work on this issue**
Yes

**Comment by hongquan** [comment]
Keep reading GPIO pin value is not efficient. GPIO pins allow "interrupt", it means that, some status of GPIO pin (at high, low, rising or falling) can emit an event and trigger some action that we registered.

In Linux, GPIO is abstracted as file (/sys/class/gpio/), so we can use [inotify](https://github.com/dsoprea/PyInotify), or Linux syscall [epoll](https://docs.python.org/3/library/select.html#select.epoll) to register an action you want to do when button is pressed / GPIO file has data to read.

**Comment by hongquan** [comment]
RPi.GPIO has higher level implementation: https://sourceforge.net/p/raspberry-gpio-python/wiki/Inputs/ (read "Interrupts and Edge detection" section).
