### ISSUE TITLE
Error while setting up on Ubuntu

### ISSUE THREAD

**Issue by techytushar** [fossasia/susi_linux#306]
**Describe the bug**
When I run `python config-generator.py` it generates an `Index Error` . My OS is Ubuntu 16.04 and I am running the script using Python 3.6 virtualenv, screenshot is attached below.

**To Reproduce**
1. Fork and clone `susi_linux` repo.
2. Setup Python 3.6 virtualenv and run `./install.sh` successfully
3. Test the audio, working fine. 
4. Run `python config_generator.py` and see the errror

**Expected behavior**
The script should run without any errors.

**Screenshots**
![screenshot from 2018-07-27 13-18-31](https://user-images.githubusercontent.com/26834658/43308786-44b6b4de-91a0-11e8-8c2f-b8115ebdefd0.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - Browser [Firefox Quantam]
 - Version [61.0.1 (64-bit)]

**Comment by stealthanthrax** [comment]
@techytushar , you have to run `python3 config_genereator.py <stt_choice> <tts_choice> <hotword> <wake_button>`. You will get some instructions when you use `./install.sh` . 
This is the correct behaviour
