### ISSUE TITLE
Implement action types pause, resume and restart

### ISSUE THREAD

**Issue by Orbiter** [fossasia/susi_linux#309]
**Describe the solution you'd like**
If a media file is played, it is possible to say "stop" to stop playing. Similarly, with the following action types, it should be possible to
* **pause** the playing of a media file (youtube, mp3 etc) with the action type `pause`
* **resume** the playing of a media file which has been paused with the action type `resume`
* **restart** the playing of a media file (either currently playing or paused) with the action type `restart`

**Additional context**
Examples:
`https://api.susi.ai/susi/chat.json?q=pause`
```
"actions": [{"type": "pause"}]
```

`https://api.susi.ai/susi/chat.json?q=resume`
```
"actions": [{"type": "resume"}]
```

`https://api.susi.ai/susi/chat.json?q=restart`
```
"actions": [{"type": "restart"}]
```

**Comment by stealthanthrax** [comment]
I would like to work on it

**Comment by stealthanthrax** [comment]
@Orbiter , right now we pause the Music to process the second query. Now we would have to follow a different approach. Should we be reducing the volume of the music player instead??

**Comment by hongquan** [comment]
> have to follow a different approach

@stealthanthrax Can I learn more about the context? Which approach is that? Where is it described?

**Comment by tmccormi** [comment]
Adding an action to change the volume up and down seems to be relevant for this feature request as well
