### ISSUE TITLE
Simplify sequence of running scripts

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#324]
In many places, I see that you are executing scripts in this way

Script A (Python) -> Wrapper script W (shell) -> Script B

Why do you have to add 1 more layer with shell script? Doing so, the OS have to launch 1 more process and cost more resource.

Let's simplify to

- Script A -> Script B
- Or better, import function from Script B and call in script A (no more process is launched).

**Comment by prateekiiest** [comment]
@stealthanthrax please add any revert label here. We would look into the current bug and until that let the wrapper scripts exist

**Comment by stealthanthrax** [comment]
Closing as this issue is solved.
