### ISSUE TITLE
One dependency error which is making SUSI startup service to crash

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#328]
**Describe the bug**
Python module service_identity not present and hence Startup script not working

**To Reproduce**
Restart the raspi and SUSI won't work

**Expected behavior**
To work on Startup

**Additional context**
I would like to work on this

**Comment by hongquan** [comment]
Why don't you provide a log?
Without the log, I cannot see what is wrong.

**Comment by stealthanthrax** [comment]
@hongquan , it was an outdated pip module. Now as I have updated it in my System , I am unable to get the error again and hence unable to get the log

**Comment by hongquan** [comment]
Ok
