### ISSUE TITLE
To Open the StartUp play sound with the python module

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#331]
**Is your feature request related to a problem? Please describe.**
Right Now the startup sound is played as an external service but I would like it to be played every time SUSI Linux is started. This will also reduce the hindrance provided due to the service bootup.

**Describe the solution you'd like**
To play the sound from the python program, every time we start SUSI Linux. Also, change it to a different sound, as right now it sounds too mechanical.

**Additional context**
I would like to take this up.

**Comment by stealthanthrax** [comment]
@mariobehling @Orbiter @hongquan , should we implement it this way ??

**Comment by hongquan** [comment]
I thought "every time SUSI Linux is started" is the same "every time the RPi is boot up"?

For the final product, does user have any method to restart the "susi linux" alone, without reboot the RPi hardware?

**Comment by stealthanthrax** [comment]
No @hongquan , the user does not have to start SUSI Linux independently , but I was using it for the development
