### ISSUE TITLE
To update the documentation regarding the Flask Server

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#332]
**Is your feature request related to a problem? Please describe.**
Documentation regarding SUSI Flask Server outdated

**Describe the solution you'd like**
To Update the documentation

**Additional context**
I would like to take this up

**Comment by VishalSharma0309** [comment]
Can I work on this?

**Comment by stealthanthrax** [comment]
Sure @VishalSharma0309 , go ahead 👍

**Comment by stealthanthrax** [comment]
Taking up this issue

**Comment by stealthanthrax** [comment]
Fixed Here https://github.com/fossasia/susi_linux/pull/455
