### ISSUE TITLE
SUSI Server not compiling on Raspberry Pi

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#354]
**Describe the bug**
Due to some issues gradle is failing on Raspi

**To Reproduce**
1. ./gradlew build

**Expected behavior**
To make it work again

**Additional context**

**Comment by hongquan** [comment]
How is the issue? (This is not the first time I ask for detail or log).

**Comment by stealthanthrax** [comment]
This issue has been fixed on the server.
