### ISSUE TITLE
Config flask server is not working after removal of wrappers

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#355]
**Is your feature request related to a problem? Please describe.**
After the shell wrappers were removed, the flask server doesn't create config.json file.

**Describe the solution you'd like**
To fix it.

**Additional context**
Yes

**Comment by mariobehling** [comment]
Use journalctl to see the route from systemd and provide more info. Currently it is unclear how to reproduces this.

**Comment by mariobehling** [comment]
It stopped working after PR https://github.com/fossasia/susi_linux/pull/334 was merged.

**Comment by mariobehling** [comment]
Related to https://github.com/fossasia/susi_linux/issues/324

**Comment by prateekiiest** [comment]
I have tried reverting the changes but its not possible I see. Somehow it has been reverted I see from the github message

**Comment by prateekiiest** [comment]
@stealthanthrax did you locate why the error is happening?

We need to check any sort of dependancy between the flask server creation of json file wrt to the wrapper script removal

**Comment by stealthanthrax** [comment]
@prateekiiest , I still am trying to figure it out. It most probably looks like a directory issue.
