### ISSUE TITLE
susi_linux failed to start on boot

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#363]
**Describe the bug**
susi_linux failed to start when RPi boot up.
From the log (https://paste.ee/p/CyiJ4), there are some issues:

- Try to connect to SUSI server when SUSI server is not ready (not listen port 4000 yet).
- Try to play audio when Jack server is not ready yet.
- Crash when microphone is not connected.

**Comment by hongquan** [comment]
It seems that ReSpeaker driver is not installed properly on my RPi.

**Comment by hongquan** [comment]
@stealthanthrax Why not look into the log I pasted above:

> Sep 01 19:20:59 raspberrypi python3[540]: Cannot connect to server socket err = No such file or directory
> Sep 01 19:20:59 raspberrypi python3[540]: Cannot connect to server request channel
> Sep 01 19:20:59 raspberrypi python3[540]: jack server is not running or cannot be started
> Sep 01 19:20:59 raspberrypi python3[540]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock

**Comment by stealthanthrax** [comment]
@hongquan , I think we can ignore those logs as they are an issue from Snowboy side and not on our side and SUSI work's fine with these logs

**Comment by hongquan** [comment]
@stealthanthrax You should specify which issue can be ignored.
With the 3rd issue, SUSI Linux crashes, we cannot ignore, because how come it work when it failed to start?

**Comment by stealthanthrax** [comment]
@hongquan , i was referring to this issue
>Try to play audio when Jack server is not ready yet.

**Comment by stealthanthrax** [comment]
@hongquan , can this be closed now??

**Comment by hongquan** [comment]
Close, because the problems no longer happen, and the "jack server" seems to be PyAudio's false report.
