### ISSUE TITLE
Using libportaudio instead of SOX libraries

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#364]
**Describe the bug**
SUSI Linux doesn't play audio and crashes out when built on raspbian lite.

**To Reproduce**
1. Build SUSI Linux on raspbian lite
2. The program will abort out

**Expected behavior**
To try and use libportaudio to play music

**Additional context**
I would like to take this up

**Comment by hongquan** [comment]
There is another case: The music player uses ALSA directly, instead of going through PulseAudio.
