### ISSUE TITLE
SUSI Linux not working from the command line

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#383]
**Describe the bug**
SUSI Linux not working from the command line and crashes out giving the log below.

**To Reproduce**
1. Start SUSI Linux with the command 'python3 -m main'

**Expected behavior**
To make it work again

**Log**
`
Sep 01 19:20:59 raspberrypi python3[540]: Cannot connect to server socket err = No such file or directory
Sep 01 19:20:59 raspberrypi python3[540]: Cannot connect to server request channel
Sep 01 19:20:59 raspberrypi python3[540]: jack server is not running or cannot be started
Sep 01 19:20:59 raspberrypi python3[540]: JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
`

**Additional context**

**Comment by hongquan** [comment]
Those log are from PyAudio and seem to be just false report.
The log related to "SUSI not working from command line" may be other log and you should debug again.

**Comment by stealthanthrax** [comment]
Closing this as this was a random One time issue
