### ISSUE TITLE
Youtube audio takes a long time to start

### ISSUE THREAD

**Issue by sansyrox** [fossasia/susi_linux#384]
**Describe the bug**
There is a large delay of youtube music even with a strong internet connection.

**To Reproduce**
Start Speaker
1. Ask SUSI to play a song from youtube

**Expected behavior**
To fix the delay and figure out the problem

**Additional context**
To check if its the problem in Raspberry Pi hardware capabilities or in the music player

**Comment by stealthanthrax** [comment]
https://www.youtube.com/watch?v=bCOc8IS0Uq8

**Comment by stealthanthrax** [comment]
As suggested by @cweitat , https://stackoverflow.com/questions/49354232/stream-youtube-audio-from-python-using-url-without-downloading-python/49354406#49354406 

We can use this method, also we can create a simple media server as an add-on to integrate the play and pause features

**Comment by hongquan** [comment]
[`pafy`](https://github.com/mps-youtube/pafy) actually uses `youtube-dl` under the hood. So, you still can use `youtube-dl` to retrieve the streaming URL.
