### ISSUE TITLE
web search responses are not working 

### ISSUE THREAD

**Issue by kasojumounika** [fossasia/susi_linux#390]
susi ai speaker could not get information from web search.

**To Reproduce**
1.say susi.
2. What is famous in Hyderabad.
3. It just processes the web query but doesn't give the answer.

**Expected behavior**
As i questioned what famous in hyderabad.i expected susi to answer Charminar. Charminar is a historic monument in Hyderabad. ...
Falaknuma Palace. Falaknuma Palace. ...
Qutub Shahi Tombs.

**Screenshots**
NA

**Desktop (please complete the following information):**
NA

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kasojumounika** [comment]
I would like to work on this issue.

**Comment by stealthanthrax** [comment]
sure ,@kasojmounika :+1:

**Comment by stealthanthrax** [comment]
I would like to work on this due to inactivity.

**Comment by stealthanthrax** [comment]
This issue has been fixed by a server update and hence closing it.
