### ISSUE TITLE
Add support for pocketsphinx for wakeword detection

### ISSUE THREAD

**Issue by ftyers** [fossasia/susi_linux#399]
**Is your feature request related to a problem? Please describe.**

It's frustrating to rely on non-free software.

**Describe the solution you'd like**

Let's use free software for the wakeword detection, like [pocketsphinx](https://github.com/cmusphinx/pocketsphinx) or something else.

**Comment by prateekiiest** [comment]
we are using pocketsphinx for stopword detection

**Comment by ftyers** [comment]
I understood that [snowboy](https://snowboy.kitt.ai/) was being used. Perhaps I am mistaken?

**Comment by prateekiiest** [comment]
As for the time being, we are using both options depending on whether the user has snowboy installed or not.

https://github.com/fossasia/susi_linux/blob/87d4495bf0041d6cab85af06c5de24153e3b1cb3/main/hotword_engine/__init__.py

so you can switch to any one of them, upon your wish.

The pocketsphinx implementation is here https://github.com/fossasia/susi_linux/blob/62b23b1147a8ef22bb08f2ad97b0772e3681d43e/main/hotword_engine/sphinx_detector.py
