### ISSUE TITLE
Wakeword detection on RPI Device is too fuzzy

### ISSUE THREAD

**Issue by tmccormi** [fossasia/susi_linux#402]
Any number of sounds that are not the word SUSI pronounced by me including parts of english sentences and even random humming (which I do a lot) wake up the device.

To reproduce, just have one on in the room and have normal conversations with people.  Or just say the word Fuzzy ...

**Expected behavior**
Wakeup should only happen (mostly) with a clearly recognized word. 

**Desktop (please complete the following information):**
None

**Smartphone (please complete the following information):**
N/A

Suggestion:  Make the wake word two words (like google does)  "OK SUSI" or whatever.

**Comment by tmccormi** [comment]
Seriously, clearing my throat triggers SUSI :-)

**Comment by stealthanthrax** [comment]
@tmccormi , a possible fix would be to reduce the sensitivity of the hotword detection to a lower scale and train the model with different accents

**Comment by stealthanthrax** [comment]
Fixed here : [link](https://github.com/fossasia/susi_linux/issues/399)
