### ISSUE TITLE
Song not played due to wrong communication

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#413]
**Describe the bug**

This bug is introduced by #391.
When speaking to susi_linux: "play cheerleader", the main module calls music_server API with "/song/ytd-jGflUbPQfW8" URL. But this URL is not recognized by music_server.

The code
https://github.com/fossasia/susi_linux/blob/06fd30002091e3422252040d526180643abc066c/youtube_player/music_server.py#L15-L17

clearly shows that, this module expects URL as `/song?vid=jGflUbPQfW8`, not `/song/ytd-jGflUbPQfW8`.

I doubt @stealthanthrax carefully tested his code before making PR.

**To Reproduce**
1. Stop susi_linux systemd service
2. Run susi_linux manually (with command `python3 -m main`)
3. Run `journalctl -fu ss-susi-youtube.service` to see this service's log.
4. Speak "susi play cheerleader" to SUSI (actually, I spoke "susi play soledad", but Google STT somehow misunderstood me).
5. Look into _ss-susi-youtube.service_ log, I saw this log:

```
Nov 12 18:38:31 quan-pi-two python3[5814]: 127.0.0.1 - - [12/Nov/2018 18:38:31] "GET /song/ytd-jGflUbPQfW8 HTTP/1.1" 404 -
```

**Expected behavior**
susi_linux main module should call correct URL and the song is played.

**Comment by stealthanthrax** [comment]
Fixed here : [link](https://github.com/fossasia/susi_linux/pull/415)
