### ISSUE TITLE
It is hard to wake up SUSI with hotword

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#424]
**Describe the bug**
The hotword detection seems not working well. When I call "SUSI", it often not recognize my voice (success rate is about 1/10). When I and my friends are talking nearby, sometimes SUSI thinks that we call it and it responds.

**Additional context**
Maybe we have to train `snowboy` again. Don't know how the _susi.pmdl_ file is made yet.

**Comment by stealthanthrax** [comment]
@hongquan , it is made via this website https://snowboy.kitt.ai/

**Comment by hongquan** [comment]
The hotword detection works on my RPi now. The reason is that I put my RPi in a box (to protect it from dust), and it also block my voice.
