### ISSUE TITLE
To not disable lan port while in the access point mode

### ISSUE THREAD

**Issue by stealthanthrax** [fossasia/susi_linux#426]
**Describe the bug**
Currently, the lan port is disabled when the speaker is in an access point mode.

**To Reproduce**
Start the script 'wap.sh' and try to ssh via the lan port

**Expected behavior**
To not disable the lan port and alter the script accordingly

**Additional context**
I can try to resolve this issue , but as far as I remember , the raspi wifi module doesn't support access point and wifi bridge mode simultaneously.

**Comment by norbusan** [comment]
This would be resolved by PR #475
