### ISSUE TITLE
SSH is not enabled by default in the latest image

### ISSUE THREAD

**Issue by sansyrox** [fossasia/susi_linux#432]
**Describe the bug**
SSH is not enabled by default in the latest image (released on 13 Dec) which causes some issues in testing.

**To Reproduce**
1. Mount the image
2. Wait for "SUSI.AI" hotspot to appear and connect to it.
3. Try to ssh via the commands `ssh pi@raspberrypi.local or ssh pi@10.0.0.1`

**Expected behavior**
To fix this issue

**Additional context**
I'd like to fix this.

**Comment by hongquan** [comment]
Note that, "not enable SSH" is the default behavior of Raspbian, that is why there is this documentation: https://www.raspberrypi.org/documentation/remote-access/ssh/README.md

**Comment by stealthanthrax** [comment]
Yes, but we decided to add it in our script to make it easier for the devs to debug.

**Comment by hongquan** [comment]
I think this issue is not "bug" and it doesn't "causes some issues in testing". You only need to enable SSH after flashing the image and no more issue.

**Comment by stealthanthrax** [comment]
Yeah right. Maybe a feature? Cause, it would be easier for devs don't know how to enable headless ssh, and would then have to arrange an external screen.

**Comment by hongquan** [comment]
Yes, this task can be seen a feature.
And the right approach, I think, is to modify https://github.com/fossasia/pi-gen to "not disable SSH". In original Debian, if you install _openssh-server_, it will be enabled by default. Raspbian project modified this behaviour by intentionally disable SSH server,

**Comment by stealthanthrax** [comment]
@hongquan , if we enable it in the install script via `system-ctl` will it be disabled again by the pi-gen script?(if we do not modify the pi-gen script)

**Comment by hongquan** [comment]
@stealthanthrax It won't be disabled again. Your approach of "enable with systemctl" is easier to implement. Let's go with it.
