### ISSUE TITLE
Temporarily remove Travis CI

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#452]
Currently, we don't have any test case. Our Travis CI only does a trivial task: Run a part of install script, and just the easiest part: install some packages via `pip` and `apt`. It doesn't bring much value and it waste TravisCI, so I think we should suspend Travis CI until we have test case.

To test if our install script, we already have Buildkite Pipeline, which runs the whole install script, not just a part.

**Comment by norbusan** [comment]
Fixed. I have commented out the test section, and only added the trigger rebuild on susi_installer on changes in the travis.yml. Closing this issue
