### ISSUE TITLE
Enable Continuous Integration and deployment of susi_linux raspberry pi builds  

### ISSUE THREAD

**Issue by alok760** [fossasia/susi_linux#476]
#### Is your feature request related to a problem? Please describe.
Currently, the automatic builds have to run on real RPi hardware (https://buildkite.com/).
#### Describe the solution you'd like
automation of creating ready to use img files for susi_linux and implement continuous integration on TRAVIS CI.

**Comment by alok760** [comment]
i'm working on this.
progress can be checked here - https://github.com/alok760/raspbian_travis
and here - https://travis-ci.org/alok760/raspbian_travis

**Comment by hongquan** [comment]
The description is not accurate. The image is already built automatically, not manually.

![image](https://user-images.githubusercontent.com/314607/55694572-f33d3f80-59de-11e9-9489-46cce7ad1d98.png)

The only issue is that, it has to be run on real RPi hardware.

**Comment by norbusan** [comment]
DOne via susi_installer and triggers from susi_linux, susi_python, closing this issue
