### ISSUE TITLE
Clean code to match Python coding style

### ISSUE THREAD

**Issue by hongquan** [fossasia/susi_linux#482]
### Describe the bug
Currently, many parts of our code don't follow Python coding style. Now, please clean it.
Please also group and arrange the `import` lines.

### Objective
- Follow PEP8 as much as possible. For line length, it can be 120 chars (PEP8 suggests 79, but I think that number is only relevant for old display device, while all of us now use wide screen monitor).
- Don't leave unused "import", unused variable. This can be detected with _pyflakes_ tool.

### Tools
This work doesn't need much brain. So we should leave it for tools. I recommend  _pycodestyle_, _pyflakes_. They help you find problematic lines, but not fix for you. Other than that, please install appropriate plugins to your code editor to integrate the tools.

This is how you can do in VS Code:
- Install [Python](https://marketplace.visualstudio.com/items?itemName=ms-python.python) extension.
- Add this to settings:

```json
{
    "python.linting.flake8Enabled": true,
    "files.trimTrailingWhitespace": true,
    "files.insertFinalNewline": true,
    "files.trimFinalNewlines": true
}
```

**Comment by bhadreshpsavani** [comment]
May i work on this issue?

**Comment by norbusan** [comment]
@bhadreshpsavani sure enough, go ahead and send PR

**Comment by kiritka-jain** [comment]
it's been a while, @norbusan @stealthanthrax May I work on this ?

**Comment by norbusan** [comment]
Everyone can work on that, just do it and send PRs...

**Comment by yash04g** [comment]
I would like to work on this one. @stealthanthrax
