### ISSUE TITLE
stopping sound hangs device

### ISSUE THREAD

**Issue by norbusan** [fossasia/susi_linux#496]
Currently, when I tell SuSI:
```
hey susi, play some music
```
it always plays the same music on the RPi. Then, when I say
```
hey susi, stop
```
it does stop the `vlc` process, but keeps it hanging somehow occupying the sound card. Asking Susi for something new does not play the detection bell sound, but hangs, too:
```
 1580 ?        TLl    0:09 /usr/bin/vlc -I dummy https://r4---sn-ogul7n7s.googlevideo.com/videoplayback?id=o-AGCHokAMEVnVZPxrSioJNZT
 1649 ?        S      0:00 play /home/pi/SUSI.AI/susi_linux/extras/detection-bell.wav
 1655 ?        S      0:00 sox -q -t mp3 - -d trim 0.1 reverse trim 0.07 reverse tempo 1.2 pitch 2 speed 1
```

This needs improvement.

**Comment by hongquan** [comment]
Maybe we stopped VLC in a dirty way? Maybe we should tell VLC to stop the music first, then kill it?

**Comment by norbusan** [comment]
I think this should be fixed by the susi_linux audi thread rework, later on.

**Comment by alok760** [comment]
saying stop doesn't stop the song in my case
![image](https://user-images.githubusercontent.com/14289201/58387228-225c4e80-8029-11e9-84cb-b23a760dcaf0.png)

**Comment by norbusan** [comment]
fixed with recent merge of sound rework
