### ISSUE TITLE
Susi does not leave recognizing state

### ISSUE THREAD

**Issue by norbusan** [fossasia/susi_linux#513]
Susi remains indefinitely in recognizing state, even if nothing is said. We should add a timeout of say 10sec after which it transitions back to idle state.

**Comment by stealthanthrax** [comment]
@norbusan , has this issue been solved?
I'd like to take this is up, if pending.

**Comment by norbusan** [comment]
Yes please, that would be great! It is still the case, we need a timeout

**Comment by stealthanthrax** [comment]
@norbusan , what do you suggest? SUSI to transition directly back to the IDLE state or through the Error State and then reaching the IDLE state?

**Comment by norbusan** [comment]
Directly into idle state should be fine. Alexa gives a short "to-to" (very short, falling tone) when it stops recognizing. If we can have something like this it would be nice, too.
