### ISSUE TITLE
Add Documentation for detailed Raspberry Pi setup with screenshots

### ISSUE THREAD

**Issue by betterclever** [fossasia/susi_linux#55]
Documentation for the Raspberry Pi setup is still inaccurate and a lot of hidden dependencies are being missed which users encounter at time of installation.

All such dependencies are need to be installed earlier and specified so that installation is straight forward. For this, a guide with proper screenshots for each step and correct commands must be added.

I have started work on it and it will be completed by tomorrow morning (IST).

**Comment by mariobehling** [comment]
There should be rather a package that calls all the necessary dependencies instead of requesting users to install packages themselves.

**Comment by betterclever** [comment]
I am adding all the dependencies to the installation script so manual installation won't be needed. Users just need to run the script once.
