### ISSUE TITLE
Syntax error during main file execution

### ISSUE THREAD

**Issue by Donyme** [fossasia/susi_linux#97]
**Actual Behaviour**
![issue2](https://user-images.githubusercontent.com/26718351/37565024-66791f16-2ac7-11e8-8fc7-1d98bfec9814.png)
Syntax error

**Expected Behaviour**
No syntax error

Steps to produce it :
run the command python3 -m main in the susi_linux folder

**Comment by prateekiiest** [comment]
This will work with python 3 not python 2

**Comment by hongquan** [comment]
Your screenshot shows that you ran with Python 2, not 3.

And the line of code

```python
print('%s\t' % h, end='')
```

is actually for Python3, not 2.

In Python 2, `print` is language statement, not function. So, that line, if run in Python 2, will be equivalent to

```python
print ('%s\t' % h, end='')
```

where `('%s\t' % h, end='')` is a tuple. But in a tuple, there cannot be "keyword" syntax `end=''`, so `SyntaxError` is raised.

**Comment by Donyme** [comment]
Thank you! For the explantion!
